version: '3'
x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    logging: *default-logging
    container_name: ${MONGODB_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${MONGODB_PORT}
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
  mongodb_config:

networks:
  default:
    external:
      name: etl_network